---

clone:
  git:
    image: plugins/git
    tags: true

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - .git
      - dev/builder/ckbuilder
    volumes:  # mount the cache volume, needs "Trusted"
      - /tmp/cache:/cache

  tests:
    image: openjdk
    commands:
      - yum -y install git wget
      - dev/builder/build.sh

  github_release:
    image: plugins/github-release
    files: dev/builder/release/ckeditor_${DRONE_TAG}.tar.gz
    secrets: [github_token]
    checksum:
      - sha256
    when:
      event: tag

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - .git
      - dev/builder/ckbuilder
    volumes:  # mount the cache volume, needs "Trusted"
      - /tmp/cache:/cache
